# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mybusiness
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    strategy:
      matrix:
        node-version: [14, 16, 18]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Wait for MySQL to be ready
      run: |
        while ! mysqladmin ping -h "127.0.0.1" --silent; do
          sleep 1
        done

    - name: Set environment variables
      run: |
        echo DB_HOST=127.0.0.1 >> $GITHUB_ENV
        echo DB_USER=root >> $GITHUB_ENV
        echo DB_PASSWORD=root >> $GITHUB_ENV
        echo DB_NAME=mybusiness >> $GITHUB_ENV

    - name: Run tests
      run: npm test
